package mylas.com.erp.demo;
// Generated Jul 4, 2018 1:58:06 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

	private String uname;
	private Integer id;
	private String password;

	public Email() {
	}

	public Email(String uname) {
		this.uname = uname;
	}

	public Email(String uname, Integer id, String password) {
		this.uname = uname;
		this.id = id;
		this.password = password;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
