package mylas.com.erp.demo;
// Generated Jul 19, 2018 12:46:33 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * EmpDetails generated by hbm2java
 */
public class EmpDetails implements java.io.Serializable {

	private Integer id;
	private String eid;
	private String emplfirstname;
	private String empllastname;
	private String email;
	private String pswd;
	private Boolean isactive;
	private String adderss;
	private String phone;
	private String aadharno;
	private Integer createdby;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private String role;
	private String mantrans;
	private Integer departmentid;
	private Integer designationid;
	private String uname;

	public EmpDetails() {
	}

	public EmpDetails(String eid, String uname) {
		this.eid = eid;
		this.uname = uname;
	}

	public EmpDetails(String eid, String emplfirstname, String empllastname, String email, String pswd,
			Boolean isactive, String adderss, String phone, String aadharno, Integer createdby, Date createdDate,
			Integer updatedBy, Date updatedDate, String role, String mantrans, Integer departmentid,
			Integer designationid, String uname) {
		this.eid = eid;
		this.emplfirstname = emplfirstname;
		this.empllastname = empllastname;
		this.email = email;
		this.pswd = pswd;
		this.isactive = isactive;
		this.adderss = adderss;
		this.phone = phone;
		this.aadharno = aadharno;
		this.createdby = createdby;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.role = role;
		this.mantrans = mantrans;
		this.departmentid = departmentid;
		this.designationid = designationid;
		this.uname = uname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	public String getEmplfirstname() {
		return this.emplfirstname;
	}

	public void setEmplfirstname(String emplfirstname) {
		this.emplfirstname = emplfirstname;
	}

	public String getEmpllastname() {
		return this.empllastname;
	}

	public void setEmpllastname(String empllastname) {
		this.empllastname = empllastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public String getAdderss() {
		return this.adderss;
	}

	public void setAdderss(String adderss) {
		this.adderss = adderss;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAadharno() {
		return this.aadharno;
	}

	public void setAadharno(String aadharno) {
		this.aadharno = aadharno;
	}

	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getMantrans() {
		return this.mantrans;
	}

	public void setMantrans(String mantrans) {
		this.mantrans = mantrans;
	}

	public Integer getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public Integer getDesignationid() {
		return this.designationid;
	}

	public void setDesignationid(Integer designationid) {
		this.designationid = designationid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

}
