package mylas.com.erp.demo;
// Generated 14 Jun, 2018 2:22:36 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmpDetails generated by hbm2java
 */
@Entity
@Table(name = "emp_details", schema = "dbo", catalog = "mylasfyt_krishna", uniqueConstraints = {
		@UniqueConstraint(columnNames = "eid"), @UniqueConstraint(columnNames = "uname") })
public class EmpDetails implements java.io.Serializable {

	public Integer id;
	private String compName;
	private String cpswd;
	private String designation;
	private String eid;
	private String email;
	public String fname;
	private String jdate;
	public String lname;
	private boolean loginStatus;
	private String phone;
	private String pswd;
	private String role;
	private String uname;
	private String managerid;
	private String department;
	private String mantrans;
	private String lastworkingday;

	public EmpDetails() {
	}

	public EmpDetails(String eid, boolean loginStatus, String uname) {
		this.eid = eid;
		this.loginStatus = loginStatus;
		this.uname = uname;
	}

	public EmpDetails(String compName, String cpswd, String designation, String eid, String email, String fname,
			String jdate, String lname, boolean loginStatus, String phone, String pswd, String role, String uname,
			String managerid, String department, String mantrans, String lastworkingday) {
		this.compName = compName;
		this.cpswd = cpswd;
		this.designation = designation;
		this.eid = eid;
		this.email = email;
		this.fname = fname;
		this.jdate = jdate;
		this.lname = lname;
		this.loginStatus = loginStatus;
		this.phone = phone;
		this.pswd = pswd;
		this.role = role;
		this.uname = uname;
		this.managerid = managerid;
		this.department = department;
		this.mantrans = mantrans;
		this.lastworkingday = lastworkingday;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "compName", length = 50)
	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	@Column(name = "cpswd", length = 50)
	public String getCpswd() {
		return this.cpswd;
	}

	public void setCpswd(String cpswd) {
		this.cpswd = cpswd;
	}

	@Column(name = "designation", length = 50)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "eid", unique = true, nullable = false, length = 50)
	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fname", length = 50)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "jdate", length = 50)
	public String getJdate() {
		return this.jdate;
	}

	public void setJdate(String jdate) {
		this.jdate = jdate;
	}

	@Column(name = "lname", length = 50)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "login_status", nullable = false)
	public boolean isLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(boolean loginStatus) {
		this.loginStatus = loginStatus;
	}

	@Column(name = "phone", length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "pswd", length = 50)
	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	@Column(name = "role", length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "uname", unique = true, nullable = false, length = 50)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "managerid", length = 50)
	public String getManagerid() {
		return this.managerid;
	}

	public void setManagerid(String managerid) {
		this.managerid = managerid;
	}

	@Column(name = "department", length = 50)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "mantrans", length = 50)
	public String getMantrans() {
		return this.mantrans;
	}

	public void setMantrans(String mantrans) {
		this.mantrans = mantrans;
	}

	@Column(name = "lastworkingday", length = 50)
	public String getLastworkingday() {
		return this.lastworkingday;
	}

	public void setLastworkingday(String lastworkingday) {
		this.lastworkingday = lastworkingday;
	}

}
