 package mylas.com.erp.demo;
// Generated Jul 18, 2018 12:10:13 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * EmpDetails generated by hbm2java
 */
public class EmpDetails implements java.io.Serializable {

	private Integer id;
	private String eid;
	private String emplfirstname;
	private String empllastname;
	private String email;
	private String pswd;
	private Boolean isactive;
	private String address;
	private String phone;
	private String aadharno;
	private String createdby;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String role;
	private String uname;
	private Integer departmentid;
	private Integer designationid;
	private Integer superiorid;

	public EmpDetails() {
	}

	public EmpDetails(String eid, String uname) {
		this.eid = eid;
		this.uname = uname;
	}

	public EmpDetails(String eid, String emplfirstname, String empllastname, String email, String pswd,
			Boolean isactive, String address, String phone, String aadharno, String createdby, Date createdDate,
			String updatedBy, Date updatedDate, String role, String uname, Integer departmentid, Integer designationid,
			Integer superiorid) {
		this.eid = eid;
		this.emplfirstname = emplfirstname;
		this.empllastname = empllastname;
		this.email = email;
		this.pswd = pswd;
		this.isactive = isactive;
		this.address = address;
		this.phone = phone;
		this.aadharno = aadharno;
		this.createdby = createdby;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.role = role;
		this.uname = uname;
		this.departmentid = departmentid;
		this.designationid = designationid;
		this.superiorid = superiorid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	public String getEmplfirstname() {
		return this.emplfirstname;
	}

	public void setEmplfirstname(String emplfirstname) {
		this.emplfirstname = emplfirstname;
	}

	public String getEmpllastname() {
		return this.empllastname;
	}

	public void setEmpllastname(String empllastname) {
		this.empllastname = empllastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAadharno() {
		return this.aadharno;
	}

	public void setAadharno(String aadharno) {
		this.aadharno = aadharno;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public Integer getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public Integer getDesignationid() {
		return this.designationid;
	}

	public void setDesignationid(Integer designationid) {
		this.designationid = designationid;
	}

	public Integer getSuperiorid() {
		return this.superiorid;
	}

	public void setSuperiorid(Integer superiorid) {
		this.superiorid = superiorid;
	}

}
