package mylas.com.erp.demo;
// Generated 14 Jun, 2018 5:15:27 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Holidays generated by hbm2java
 */
@Entity
@Table(name = "holidays", schema = "dbo", catalog = "mylasfyt_krishna")
public class Holidays implements java.io.Serializable {

	private Integer id;
	private String name;
	private String date;
	private String month;
	private String year;

	public Holidays() {
	}

	public Holidays(String name, String date, String month, String year) {
		this.name = name;
		this.date = date;
		this.month = month;
		this.year = year;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "date", length = 50)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "month", length = 50)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "Year", length = 50)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
