package mylas.com.erp.demo;
// Generated Jul 19, 2018 12:46:33 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * TblDesignation generated by hbm2java
 */
public class TblDesignation implements java.io.Serializable {

	private Integer designationid;
	private String designation;
	private String departmentname;
	private Boolean isactive;
	private Integer createdBy;
	private Date createddate;
	private Integer updatedby;
	private Date updateddate;

	public TblDesignation() {
	}

	public TblDesignation(String designation, String departmentname) {
		this.designation = designation;
		this.departmentname = departmentname;
	}

	public TblDesignation(String designation, String departmentname, Boolean isactive, Integer createdBy,
			Date createddate, Integer updatedby, Date updateddate) {
		this.designation = designation;
		this.departmentname = departmentname;
		this.isactive = isactive;
		this.createdBy = createdBy;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	public Integer getDesignationid() {
		return this.designationid;
	}

	public void setDesignationid(Integer designationid) {
		this.designationid = designationid;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDepartmentname() {
		return this.departmentname;
	}

	public void setDepartmentname(String departmentname) {
		this.departmentname = departmentname;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
