package mylas.com.erp.demo;
// Generated 19 Jun, 2018 10:51:25 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblDesignation generated by hbm2java
 */
@Entity
@Table(name = "tbl_Designation", schema = "dbo", catalog = "mylasfyt_krishna")
public class TblDesignation implements java.io.Serializable {

	private Integer designationId;
	private String designation;
	private String department;
	private String fromdate;
	private String todate;
	private Boolean activestate;

	public TblDesignation() {
	}

	public TblDesignation(String designation, String department, String fromdate, String todate, Boolean activestate) {
		this.designation = designation;
		this.department = department;
		this.fromdate = fromdate;
		this.todate = todate;
		this.activestate = activestate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DesignationId", unique = true, nullable = false)
	public Integer getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(Integer designationId) {
		this.designationId = designationId;
	}

	@Column(name = "Designation", length = 50)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "department", length = 55)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "fromdate", length = 50)
	public String getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}

	@Column(name = "todate", length = 50)
	public String getTodate() {
		return this.todate;
	}

	public void setTodate(String todate) {
		this.todate = todate;
	}

	@Column(name = "activestate")
	public Boolean getActivestate() {
		return this.activestate;
	}

	public void setActivestate(Boolean activestate) {
		this.activestate = activestate;
	}

}
