package mylas.com.erp.demo;
// Generated Jul 3, 2018 3:19:21 PM by Hibernate Tools 5.3.0.Beta2

/**
 * TblDesignation generated by hbm2java
 */
public class TblDesignation implements java.io.Serializable {

	private Integer designationId;
	private String designation;
	private String department;
	private String fromdate;
	private String todate;
	private Boolean activestate;

	public TblDesignation() {
	}

	public TblDesignation(String designation, String department, String fromdate, String todate, Boolean activestate) {
		this.designation = designation;
		this.department = department;
		this.fromdate = fromdate;
		this.todate = todate;
		this.activestate = activestate;
	}

	public Integer getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(Integer designationId) {
		this.designationId = designationId;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}

	public String getTodate() {
		return this.todate;
	}

	public void setTodate(String todate) {
		this.todate = todate;
	}

	public Boolean getActivestate() {
		return this.activestate;
	}

	public void setActivestate(Boolean activestate) {
		this.activestate = activestate;
	}

}
