package mylas.com.erp.demo;
// Generated Jul 19, 2018 12:46:33 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * TblDepartment generated by hbm2java
 */
public class TblDepartment implements java.io.Serializable {

	private Integer departmentid;
	private String departmentname;
	private Boolean isactive;
	private Integer createdby;
	private Date createddate;
	private Integer updatedby;
	private Date updateddate;

	public TblDepartment() {
	}

	public TblDepartment(String departmentname) {
		this.departmentname = departmentname;
	}

	public TblDepartment(String departmentname, Boolean isactive, Integer createdby, Date createddate,
			Integer updatedby, Date updateddate) {
		this.departmentname = departmentname;
		this.isactive = isactive;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	public Integer getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public String getDepartmentname() {
		return this.departmentname;
	}

	public void setDepartmentname(String departmentname) {
		this.departmentname = departmentname;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
