package mylas.com.erp.demo;// default package
// Generated Jul 26, 2018 12:22:14 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * TblEmpattendanceNew generated by hbm2java
 */
public class TblEmpattendanceNew implements java.io.Serializable {

	private Integer id;
	private Integer managerid;
	private Integer monthid;
	private String empname;
	private String empno;
	private Integer yearid;
	private Integer createdby;
	private Date createddate;
	private Integer updatedby;
	private Date updateddate;
	private Integer day1;
	private Integer day2;
	private Integer day3;
	private Integer day4;
	private Integer day5;
	private Integer day6;
	private Integer day7;
	private Integer day8;
	private Integer day9;
	private Integer day10;
	private Integer day11;
	private Integer day12;
	private Integer day13;
	private Integer day14;
	private Integer day15;
	private Integer day16;
	private Integer day17;
	private Integer day18;
	private Integer day19;
	private Integer day20;
	private Integer day21;
	private Integer day22;
	private Integer day23;
	private Integer day24;
	private Integer day25;
	private Integer day26;
	private Integer day27;
	private Integer day28;
	private Integer day29;
	private Integer day30;
	private Integer day31;
	private String status;

	public TblEmpattendanceNew() {
	}

	public TblEmpattendanceNew(Integer managerid, Integer monthid, String empname, String empno, Integer yearid,
			Integer createdby, Date createddate, Integer updatedby, Date updateddate, Integer day1, Integer day2,
			Integer day3, Integer day4, Integer day5, Integer day6, Integer day7, Integer day8, Integer day9,
			Integer day10, Integer day11, Integer day12, Integer day13, Integer day14, Integer day15, Integer day16,
			Integer day17, Integer day18, Integer day19, Integer day20, Integer day21, Integer day22, Integer day23,
			Integer day24, Integer day25, Integer day26, Integer day27, Integer day28, Integer day29, Integer day30,
			Integer day31, String status) {
		this.managerid = managerid;
		this.monthid = monthid;
		this.empname = empname;
		this.empno = empno;
		this.yearid = yearid;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.day1 = day1;
		this.day2 = day2;
		this.day3 = day3;
		this.day4 = day4;
		this.day5 = day5;
		this.day6 = day6;
		this.day7 = day7;
		this.day8 = day8;
		this.day9 = day9;
		this.day10 = day10;
		this.day11 = day11;
		this.day12 = day12;
		this.day13 = day13;
		this.day14 = day14;
		this.day15 = day15;
		this.day16 = day16;
		this.day17 = day17;
		this.day18 = day18;
		this.day19 = day19;
		this.day20 = day20;
		this.day21 = day21;
		this.day22 = day22;
		this.day23 = day23;
		this.day24 = day24;
		this.day25 = day25;
		this.day26 = day26;
		this.day27 = day27;
		this.day28 = day28;
		this.day29 = day29;
		this.day30 = day30;
		this.day31 = day31;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getManagerid() {
		return this.managerid;
	}

	public void setManagerid(Integer managerid) {
		this.managerid = managerid;
	}

	public Integer getMonthid() {
		return this.monthid;
	}

	public void setMonthid(Integer monthid) {
		this.monthid = monthid;
	}

	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public String getEmpno() {
		return this.empno;
	}

	public void setEmpno(String empno) {
		this.empno = empno;
	}

	public Integer getYearid() {
		return this.yearid;
	}

	public void setYearid(Integer yearid) {
		this.yearid = yearid;
	}

	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Integer getDay1() {
		return this.day1;
	}

	public void setDay1(Integer day1) {
		this.day1 = day1;
	}

	public Integer getDay2() {
		return this.day2;
	}

	public void setDay2(Integer day2) {
		this.day2 = day2;
	}

	public Integer getDay3() {
		return this.day3;
	}

	public void setDay3(Integer day3) {
		this.day3 = day3;
	}

	public Integer getDay4() {
		return this.day4;
	}

	public void setDay4(Integer day4) {
		this.day4 = day4;
	}

	public Integer getDay5() {
		return this.day5;
	}

	public void setDay5(Integer day5) {
		this.day5 = day5;
	}

	public Integer getDay6() {
		return this.day6;
	}

	public void setDay6(Integer day6) {
		this.day6 = day6;
	}

	public Integer getDay7() {
		return this.day7;
	}

	public void setDay7(Integer day7) {
		this.day7 = day7;
	}

	public Integer getDay8() {
		return this.day8;
	}

	public void setDay8(Integer day8) {
		this.day8 = day8;
	}

	public Integer getDay9() {
		return this.day9;
	}

	public void setDay9(Integer day9) {
		this.day9 = day9;
	}

	public Integer getDay10() {
		return this.day10;
	}

	public void setDay10(Integer day10) {
		this.day10 = day10;
	}

	public Integer getDay11() {
		return this.day11;
	}

	public void setDay11(Integer day11) {
		this.day11 = day11;
	}

	public Integer getDay12() {
		return this.day12;
	}

	public void setDay12(Integer day12) {
		this.day12 = day12;
	}

	public Integer getDay13() {
		return this.day13;
	}

	public void setDay13(Integer day13) {
		this.day13 = day13;
	}

	public Integer getDay14() {
		return this.day14;
	}

	public void setDay14(Integer day14) {
		this.day14 = day14;
	}

	public Integer getDay15() {
		return this.day15;
	}

	public void setDay15(Integer day15) {
		this.day15 = day15;
	}

	public Integer getDay16() {
		return this.day16;
	}

	public void setDay16(Integer day16) {
		this.day16 = day16;
	}

	public Integer getDay17() {
		return this.day17;
	}

	public void setDay17(Integer day17) {
		this.day17 = day17;
	}

	public Integer getDay18() {
		return this.day18;
	}

	public void setDay18(Integer day18) {
		this.day18 = day18;
	}

	public Integer getDay19() {
		return this.day19;
	}

	public void setDay19(Integer day19) {
		this.day19 = day19;
	}

	public Integer getDay20() {
		return this.day20;
	}

	public void setDay20(Integer day20) {
		this.day20 = day20;
	}

	public Integer getDay21() {
		return this.day21;
	}

	public void setDay21(Integer day21) {
		this.day21 = day21;
	}

	public Integer getDay22() {
		return this.day22;
	}

	public void setDay22(Integer day22) {
		this.day22 = day22;
	}

	public Integer getDay23() {
		return this.day23;
	}

	public void setDay23(Integer day23) {
		this.day23 = day23;
	}

	public Integer getDay24() {
		return this.day24;
	}

	public void setDay24(Integer day24) {
		this.day24 = day24;
	}

	public Integer getDay25() {
		return this.day25;
	}

	public void setDay25(Integer day25) {
		this.day25 = day25;
	}

	public Integer getDay26() {
		return this.day26;
	}

	public void setDay26(Integer day26) {
		this.day26 = day26;
	}

	public Integer getDay27() {
		return this.day27;
	}

	public void setDay27(Integer day27) {
		this.day27 = day27;
	}

	public Integer getDay28() {
		return this.day28;
	}

	public void setDay28(Integer day28) {
		this.day28 = day28;
	}

	public Integer getDay29() {
		return this.day29;
	}

	public void setDay29(Integer day29) {
		this.day29 = day29;
	}

	public Integer getDay30() {
		return this.day30;
	}

	public void setDay30(Integer day30) {
		this.day30 = day30;
	}

	public Integer getDay31() {
		return this.day31;
	}

	public void setDay31(Integer day31) {
		this.day31 = day31;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
