package mylas.com.erp.demo;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblEmpLeavereq generated by hbm2java
 */
@Entity
@Table(name = "tbl_emp_leavereq", schema = "dbo", catalog = "mylasfyt_krishna")
public class TblEmpLeavereq implements java.io.Serializable {

	private Integer id;
	private Integer count;
	private String employeeid;
	private String fromdate;
	private String leavereason;
	private String leavetype;
	private String managerid;
	private Boolean status;
	private String todate;
	private String reason;
	private String mantrans;

	public TblEmpLeavereq() {
	}

	public TblEmpLeavereq(Integer count, String employeeid, String fromdate, String leavereason, String leavetype,
			String managerid, Boolean status, String todate, String reason, String mantrans) {
		this.count = count;
		this.employeeid = employeeid;
		this.fromdate = fromdate;
		this.leavereason = leavereason;
		this.leavetype = leavetype;
		this.managerid = managerid;
		this.status = status;
		this.todate = todate;
		this.reason = reason;
		this.mantrans = mantrans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "employeeid", length = 50)
	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	@Column(name = "fromdate", length = 30)
	public String getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}

	@Column(name = "leavereason", length = 100)
	public String getLeavereason() {
		return this.leavereason;
	}

	public void setLeavereason(String leavereason) {
		this.leavereason = leavereason;
	}

	@Column(name = "leavetype", length = 15)
	public String getLeavetype() {
		return this.leavetype;
	}

	public void setLeavetype(String leavetype) {
		this.leavetype = leavetype;
	}

	@Column(name = "managerid", length = 50)
	public String getManagerid() {
		return this.managerid;
	}

	public void setManagerid(String managerid) {
		this.managerid = managerid;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "todate", length = 30)
	public String getTodate() {
		return this.todate;
	}

	public void setTodate(String todate) {
		this.todate = todate;
	}

	@Column(name = "reason", length = 150)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "mantrans", length = 50)
	public String getMantrans() {
		return this.mantrans;
	}

	public void setMantrans(String mantrans) {
		this.mantrans = mantrans;
	}

}
