package mylas.com.erp.demo;
// Generated Jul 17, 2018 4:44:28 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * TblEmployees generated by hbm2java
 */
public class TblEmployees implements java.io.Serializable {

	private Integer eid;
	private String empid;
	private String emplfirstname;
	private String empllastname;
	private String email;
	private String password;
	private Boolean isactive;
	private String address;
	private String mobileno;
	private String aadharno;
	private String createdby;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String role;
	private String magrtranferid;
	private String department;
	private String designation;
	private String username;

	public TblEmployees() {
	}

	public TblEmployees(String username) {
		this.username = username;
	}

	public TblEmployees(String empid, String emplfirstname, String empllastname, String email, String password,
			Boolean isactive, String address, String mobileno, String aadharno, String createdby, Date createdDate,
			String updatedBy, Date updatedDate, String role, String magrtranferid, String department,
			String designation, String username) {
		this.empid = empid;
		this.emplfirstname = emplfirstname;
		this.empllastname = empllastname;
		this.email = email;
		this.password = password;
		this.isactive = isactive;
		this.address = address;
		this.mobileno = mobileno;
		this.aadharno = aadharno;
		this.createdby = createdby;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.role = role;
		this.magrtranferid = magrtranferid;
		this.department = department;
		this.designation = designation;
		this.username = username;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public String getEmpid() {
		return this.empid;
	}

	public void setEmpid(String empid) {
		this.empid = empid;
	}

	public String getEmplfirstname() {
		return this.emplfirstname;
	}

	public void setEmplfirstname(String emplfirstname) {
		this.emplfirstname = emplfirstname;
	}

	public String getEmpllastname() {
		return this.empllastname;
	}

	public void setEmpllastname(String empllastname) {
		this.empllastname = empllastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public String getAadharno() {
		return this.aadharno;
	}

	public void setAadharno(String aadharno) {
		this.aadharno = aadharno;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getMagrtranferid() {
		return this.magrtranferid;
	}

	public void setMagrtranferid(String magrtranferid) {
		this.magrtranferid = magrtranferid;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
