package mylas.com.erp.demo;
// Generated Jul 19, 2018 12:46:33 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * TblHolidays generated by hbm2java
 */
public class TblHolidays implements java.io.Serializable {

	private Integer holidayid;
	private String holidayname;
	private String holidaydate;
	private Boolean isactive;
	private Integer createdby;
	private Date createddate;
	private Integer updatedby;
	private Date updateddate;

	public TblHolidays() {
	}

	public TblHolidays(String holidayname) {
		this.holidayname = holidayname;
	}

	public TblHolidays(String holidayname, String holidaydate, Boolean isactive, Integer createdby, Date createddate,
			Integer updatedby, Date updateddate) {
		this.holidayname = holidayname;
		this.holidaydate = holidaydate;
		this.isactive = isactive;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	public Integer getHolidayid() {
		return this.holidayid;
	}

	public void setHolidayid(Integer holidayid) {
		this.holidayid = holidayid;
	}

	public String getHolidayname() {
		return this.holidayname;
	}

	public void setHolidayname(String holidayname) {
		this.holidayname = holidayname;
	}

	public String getHolidaydate() {
		return this.holidaydate;
	}

	public void setHolidaydate(String holidaydate) {
		this.holidaydate = holidaydate;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
