package mylas.com.erp.demo;
// Generated Jul 16, 2018 12:32:50 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Tblleavestype generated by hbm2java
 */
public class Tblleavestype implements java.io.Serializable {

	private Integer id;
	private String leavetype;
	private Boolean isactive;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;

	public Tblleavestype() {
	}

	public Tblleavestype(String leavetype, Boolean isactive, String createdby, Date createddate, String updatedby,
			Date updateddate) {
		this.leavetype = leavetype;
		this.isactive = isactive;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLeavetype() {
		return this.leavetype;
	}

	public void setLeavetype(String leavetype) {
		this.leavetype = leavetype;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
