package mylas.com.erp.demo;
// Generated Jul 6, 2018 11:13:37 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Tblleaves generated by hbm2java
 */
public class Tblleaves implements java.io.Serializable {

	private Integer id;
	private String leavetype;
	private Integer numleavedays;

	public Tblleaves() {
	}

	public Tblleaves(String leavetype, Integer numleavedays) {
		this.leavetype = leavetype;
		this.numleavedays = numleavedays;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLeavetype() {
		return this.leavetype;
	}

	public void setLeavetype(String leavetype) {
		this.leavetype = leavetype;
	}

	public Integer getNumleavedays() {
		return this.numleavedays;
	}

	public void setNumleavedays(Integer numleavedays) {
		this.numleavedays = numleavedays;
	}

}
