package mylas.com.erp.demo;
// Generated Jul 6, 2018 11:13:37 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Tblleavestype generated by hbm2java
 */
public class Tblleavestype implements java.io.Serializable {

	private Integer id;
	private String leavetype;

	public Tblleavestype() {
	}

	public Tblleavestype(String leavetype) {
		this.leavetype = leavetype;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLeavetype() {
		return this.leavetype;
	}

	public void setLeavetype(String leavetype) {
		this.leavetype = leavetype;
	}

}
