package mylas.com.erp.demo;
// Generated Jul 12, 2018 11:02:01 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Tblleaves generated by hbm2java
 */
public class Tblleaves implements java.io.Serializable {

	private Integer id;
	private int leavetypeid;
	private Integer numleavedays;
	private Boolean isactive;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;

	public Tblleaves() {
	}

	public Tblleaves(int leavetypeid) {
		this.leavetypeid = leavetypeid;
	}

	public Tblleaves(int leavetypeid, Integer numleavedays, Boolean isactive, String createdby, Date createddate,
			String updatedby, Date updateddate) {
		this.leavetypeid = leavetypeid;
		this.numleavedays = numleavedays;
		this.isactive = isactive;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getLeavetypeid() {
		return this.leavetypeid;
	}

	public void setLeavetypeid(int leavetypeid) {
		this.leavetypeid = leavetypeid;
	}

	public Integer getNumleavedays() {
		return this.numleavedays;
	}

	public void setNumleavedays(Integer numleavedays) {
		this.numleavedays = numleavedays;
	}

	public Boolean getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
