package mylas.com.erp.demo;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblManRoleTransfer generated by hbm2java
 */
@Entity
@Table(name = "tbl_man_role_transfer", schema = "dbo", catalog = "mylasfyt_krishna")
public class TblManRoleTransfer implements java.io.Serializable {

	private Integer id;
	private String frommanid;
	private String tomanid;
	private String fromdate;
	private String todate;
	private Integer count;
	private Boolean status;

	public TblManRoleTransfer() {
	}

	public TblManRoleTransfer(String frommanid, String tomanid, String fromdate, String todate, Integer count,
			Boolean status) {
		this.frommanid = frommanid;
		this.tomanid = tomanid;
		this.fromdate = fromdate;
		this.todate = todate;
		this.count = count;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "frommanid", length = 50)
	public String getFrommanid() {
		return this.frommanid;
	}

	public void setFrommanid(String frommanid) {
		this.frommanid = frommanid;
	}

	@Column(name = "tomanid", length = 50)
	public String getTomanid() {
		return this.tomanid;
	}

	public void setTomanid(String tomanid) {
		this.tomanid = tomanid;
	}

	@Column(name = "fromdate", length = 50)
	public String getFromdate() {
		return this.fromdate;
	}

	public void setFromdate(String fromdate) {
		this.fromdate = fromdate;
	}

	@Column(name = "todate", length = 50)
	public String getTodate() {
		return this.todate;
	}

	public void setTodate(String todate) {
		this.todate = todate;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
